version: '3'

services:
  app:
    build: ./Dockerfiles/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    build: ./Dockerfiles/db01
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postdb
    restart: always

  web01:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/project.conf
    depends_on:
      - app
    restart: always
